version: '3'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.go
      args:
        - GO_VERSION=1.19
    ports:
      - "3000:3000"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        - PYTHON_VERSION=3.11
    command: python /app/ui/hac_report.py
    ports:
      - "3001:3001"