version: '3'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.go
    ports:
      - "3000:3000"
    command: go run main.go

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    command: python hac_report.py
    ports:
      - "3001:3001"