# Dockerfile.python

FROM python:3.11-alpine as python-builder

# Set the working directory inside the container
WORKDIR /app/HAC_Assignments

# Install Python dependencies
COPY ./ui-python/requirements.txt .
RUN pip install -r requirements.txt

# Copy the Python application source code into the container
COPY ./ui-python /app/HAC_Assignments

WORKDIR /app/HAC_Assignments